baseURL = "https://docs.96rocks.com/"
languageCode = "en-US"

title = "96rocks Documentation"
theme = "docdock"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
  editURL = "https://github.com/96rocks/docs.96rocks.com/edit/master/content/"
  description = "Documentation for 96rocks project."
  author = "96rocks project"
  showVisitedLinks = true

  themeStyle = "original" # "original" or "flex" # default "flex"
  themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
  ordersectionsby = "weight" # ordersectionsby = "title"
  disableHomeIcon = false # default is false
  disableSearch = false # default is false
  disableNavChevron = false # set true to hide next/prev chevron, default is false
  highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
  menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for 96rocks"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-github'></i> Contribute"
url = "contribute"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> 96rocks.com"
url = "http://96rocks.com"
weight = 40

