baseURL = "https://96rocks.github.io/docs.96rocks.com/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "96rocks Documentation"
theme = "hugo-theme-learn"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/96rocks/docs/edit/master"
  description = "Documentation for 96rocks project."
  author = "96rocks project"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for 96rocks"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/96rocks"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> 96rocks.com"
url = "http://96rocks.com"
weight = 40

